#!/usr/bin/env python
#coding:utf-8
# Author:  mozman
# Purpose: header variables factory
# Created: 20.11.2010
# Copyright (C) 2010, Manfred Moitzi
# License: GPLv3

from functools import partial
from .tags import DXFTag, tagcast

def getvartags(varname, value):
    factory = VARMAP[varname]
    return factory(value)

def DXFValue(value, code=1):
    return tagcast( (code, value) )

def DXFPoint2D(value):
    return (DXFTag(10, value[0]), DXFTag(20, value[1]))

def DXFPoint3D(value):
    return (DXFTag(10, value[0]), DXFTag(20, value[1]), DXFTag(30, value[2]))

VARMAP = {
    '$ACADVER': partial(DXFValue, code=1),
    '$ANGBASE': partial(DXFValue, code=50),
    '$ANGDIR': partial(DXFValue, code=70),
    '$ATTDIA': partial(DXFValue, code=70),
    '$ATTMODE': partial(DXFValue, code=70),
    '$ATTREQ': partial(DXFValue, code=70),
    '$AUNITS': partial(DXFValue, code=70),
    '$AUPREC': partial(DXFValue, code=70),
    '$AXISMODE': partial(DXFValue, code=70),
    '$AXISUNIT': DXFPoint2D,
    '$BLIPMODE': partial(DXFValue, code=70),
    '$CECOLOR': partial(DXFValue, code=62),
    '$CELTYPE': partial(DXFValue, code=6),
    '$CHAMFERA': partial(DXFValue, code=40),
    '$CHAMFERB': partial(DXFValue, code=40),
    '$CLAYER': partial(DXFValue, code=8),
    '$COORDS': partial(DXFValue, code=70),
    '$DIMALT': partial(DXFValue, code=70),
    '$DIMALTD': partial(DXFValue, code=70),
    '$DIMALTF': partial(DXFValue, code=40),
    '$DIMAPOST': partial(DXFValue, code=1),
    '$DIMASO': partial(DXFValue, code=70),
    '$DIMASZ': partial(DXFValue, code=40),
    '$DIMBLK': partial(DXFValue, code=2),
    '$DIMBLK1': partial(DXFValue, code=1),
    '$DIMBLK2': partial(DXFValue, code=1),
    '$DIMCEN': partial(DXFValue, code=40),
    '$DIMCLRD': partial(DXFValue, code=70),
    '$DIMCLRE': partial(DXFValue, code=70),
    '$DIMCLRT': partial(DXFValue, code=70),
    '$DIMDLE': partial(DXFValue, code=40),
    '$DIMDLI': partial(DXFValue, code=40),
    '$DIMEXE': partial(DXFValue, code=40),
    '$DIMEXO': partial(DXFValue, code=40),
    '$DIMGAP': partial(DXFValue, code=40),
    '$DIMLFAC': partial(DXFValue, code=40),
    '$DIMLIM': partial(DXFValue, code=70),
    '$DIMPOST': partial(DXFValue, code=1),
    '$DIMRND': partial(DXFValue, code=40),
    '$DIMSAH': partial(DXFValue, code=70),
    '$DIMSCALE': partial(DXFValue, code=40),
    '$DIMSE1': partial(DXFValue, code=70),
    '$DIMSE2': partial(DXFValue, code=70),
    '$DIMSHO': partial(DXFValue, code=70),
    '$DIMSOXD': partial(DXFValue, code=70),
    '$DIMSTYLE': partial(DXFValue, code=2),
    '$DIMTAD': partial(DXFValue, code=70),
    '$DIMTFAC': partial(DXFValue, code=40),
    '$DIMTIH': partial(DXFValue, code=70),
    '$DIMTIX': partial(DXFValue, code=70),
    '$DIMTM': partial(DXFValue, code=40),
    '$DIMTOFL': partial(DXFValue, code=70),
    '$DIMTOH': partial(DXFValue, code=70),
    '$DIMTOL': partial(DXFValue, code=70),
    '$DIMTP': partial(DXFValue, code=40),
    '$DIMTSZ': partial(DXFValue, code=40),
    '$DIMTVP': partial(DXFValue, code=40),
    '$DIMTXT': partial(DXFValue, code=40),
    '$DIMZIN': partial(DXFValue, code=70),
    '$DWGCODEPAGE': partial(DXFValue, code=70),
    '$DRAGMODE': partial(DXFValue, code=70),
    '$ELEVATION': partial(DXFValue, code=40),
    '$EXTMAX': DXFPoint3D,
    '$EXTMIN': DXFPoint3D,
    '$FILLETRAD': partial(DXFValue, code=40),
    '$FILLMODE': partial(DXFValue, code=70),
    '$HANDLING': partial(DXFValue, code=70),
    '$HANDSEED': partial(DXFValue, code=5),
    '$INSBASE': DXFPoint3D,
    '$LIMCHECK': partial(DXFValue, code=70),
    '$LIMMAX': DXFPoint2D,
    '$LIMMIN': DXFPoint2D,
    '$LTSCALE': partial(DXFValue, code=40),
    '$LUNITS': partial(DXFValue, code=70),
    '$LUPREC': partial(DXFValue, code=70),
    '$MAXACTVP': partial(DXFValue, code=70),
    '$MENU': partial(DXFValue, code=1),
    '$MIRRTEXT': partial(DXFValue, code=70),
    '$ORTHOMODE': partial(DXFValue, code=70),
    '$OSMODE': partial(DXFValue, code=70),
    '$PDMODE': partial(DXFValue, code=70),
    '$PDSIZE': partial(DXFValue, code=40),
    '$PELEVATION': partial(DXFValue, code=40),
    '$PEXTMAX': DXFPoint3D,
    '$PEXTMIN': DXFPoint3D,
    '$PLIMCHECK': partial(DXFValue, code=70),
    '$PLIMMAX': DXFPoint2D,
    '$PLIMMIN': DXFPoint2D,
    '$PLINEGEN': partial(DXFValue, code=70),
    '$PLINEWID': partial(DXFValue, code=40),
    '$PSLTSCALE': partial(DXFValue, code=70),
    '$PUCSNAME': partial(DXFValue, code=2),
    '$PUCSORG': DXFPoint3D,
    '$PUCSXDIR': DXFPoint3D,
    '$PUCSYDIR': DXFPoint3D,
    '$QTEXTMODE': partial(DXFValue, code=70),
    '$REGENMODE': partial(DXFValue, code=70),
    '$SHADEDGE': partial(DXFValue, code=70),
    '$SHADEDIF': partial(DXFValue, code=70),
    '$SKETCHINC': partial(DXFValue, code=40),
    '$SKPOLY': partial(DXFValue, code=70),
    '$SPLFRAME': partial(DXFValue, code=70),
    '$SPLINESEGS': partial(DXFValue, code=70),
    '$SPLINETYPE': partial(DXFValue, code=70),
    '$SURFTAB1': partial(DXFValue, code=70),
    '$SURFTAB2': partial(DXFValue, code=70),
    '$SURFTYPE': partial(DXFValue, code=70),
    '$SURFU': partial(DXFValue, code=70),
    '$SURFV': partial(DXFValue, code=70),
    '$TDCREATE': partial(DXFValue, code=40),
    '$TDINDWG': partial(DXFValue, code=40),
    '$TDUPDATE': partial(DXFValue, code=40),
    '$TDUSRTIMER': partial(DXFValue, code=40),
    '$TEXTSIZE': partial(DXFValue, code=40),
    '$TEXTSTYLE': partial(DXFValue, code=7),
    '$THICKNESS': partial(DXFValue, code=40),
    '$TILEMODE': partial(DXFValue, code=70),
    '$TRACEWID': partial(DXFValue, code=40),
    '$UCSNAME': partial(DXFValue, code=2),
    '$UCSORG': DXFPoint3D,
    '$UCSXDIR': DXFPoint3D,
    '$UCSYDIR': DXFPoint3D,
    '$UNITMODE': partial(DXFValue, code=70),
    '$USERI1': partial(DXFValue, code=70),
    '$USERI2': partial(DXFValue, code=70),
    '$USERI3': partial(DXFValue, code=70),
    '$USERI4': partial(DXFValue, code=70),
    '$USERR1': partial(DXFValue, code=40),
    '$USERR2': partial(DXFValue, code=40),
    '$USERR3': partial(DXFValue, code=40),
    '$USERR4': partial(DXFValue, code=40),
    '$USERR5': partial(DXFValue, code=40),
    '$USRTIMER': partial(DXFValue, code=70),
    '$VISRETAIN': partial(DXFValue, code=70),
    '$WORLDVIEW': partial(DXFValue, code=70),
}