======= ========================
Version AutoCAD Release
======= ========================
AC1009  AutoCAD R12
AC1012  AutoCAD R13 (experimental; just for existing drawings - can not create new drawings)
AC1014  AutoCAD R14 (experimental; just for existing drawings - can not create new drawings)
AC1015  AutoCAD R2000
AC1018  AutoCAD R2004
AC1021  AutoCAD R2007
AC1024  AutoCAD R2010
AC1027  AutoCAD R2013
======= ========================
